# Generated by Django 5.2.8 on 2026-06-02 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_alter_promptview_unique_together_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['sort_order', 'added_at']},
        ),
        migrations.AlterUniqueTogether(
            name='promptview',
            unique_together={('prompt', 'user', 'viewed_date')},
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['visibility', 'is_removed', '-published_at'], name='prompt_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['author', '-published_at'], name='prompt_author_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-average_rating', '-published_at'], name='prompt_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-copy_count', '-published_at'], name='prompt_copy_idx'),
        ),
    ]
